music = [
  {
    title: `In the Aeroplane Over the Sea`,
    artist: `Neutral Milk Hotel`,
    year: 1998,
    length: `39:55`,
    cover: `https://upload.wikimedia.org/wikipedia/en/8/83/In_the_aeroplane_over_the_sea_album_cover_copy.jpg`,
    genre: [`indie rock`, `pyschedelic folk`, `lo-fi`],
    ten: true,
  },
  {
    title: `Twin Fantasy`,
    artist: `Car Seat Headrest`,
    year: 2011,
    length: `1:00:26`,
    cover: `https://upload.wikimedia.org/wikipedia/en/e/e0/Twin_fantasy.jpg`,
    genre: [`indie rock`, `lo-fi`, `alternative rock`],
    ten: false,
  },
  {
    title: `Loveless`,
    artist: `My Bloody Valentine`,
    year: 1991,
    length: `48:31`,
    cover: `https://upload.wikimedia.org/wikipedia/en/4/4b/My_Bloody_Valentine_-_Loveless.png?20170328161417`,
    genre: [`shoegaze`, `dream pop`, `noise rock`, `avant-rock`],
    ten: true,
  },
  {
    title: `Pinkerton`,
    artist: `Weezer`,
    year: 1996,
    length: `34:36`,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/c/ca/Pinkerton_cover.jpg/220px-Pinkerton_cover.jpg`,
    genre: [`alternative rock`, `power pop`, `emo`, `pop punk`, `lo-fi`],
    ten: true,
  },
  {
    title: `Ants from Up There`,
    artist: `Black Country, New Road`,
    year: 2022,
    length: "58:46",
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/Ants_from_Up_There_-_Black_Country%2C_New_Road.jpg/220px-Ants_from_Up_There_-_Black_Country%2C_New_Road.jpg`,
    genre: [`post-rock`, `chamber pop`, `art rock`],
    ten: false,
  },
  {
    title: `Lift Your Skinny Fists Like Antennas to Heaven`,
    artist: `Godspeed You! Black Emperor`,
    year: 2000,
    length: `87:21`,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Liftyrskinnyfists.jpg/220px-Liftyrskinnyfists.jpg`,
    genre: [`post rock`],
    ten: false,
  },
  {
    title: `Deathconsciousness`,
    artist: `Have a Nice Life`,
    year: 2008,
    length: `85:04`,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Have_a_nice_life_deathconsciousness.jpg/220px-Have_a_nice_life_deathconsciousness.jpg`,
    genre: [
      `shoegaze`,
      `post-rock`,
      `dark ambient`,
      `gothic rock`,
      `industrial rock`,
    ],
    ten: false,
  },
];
