export const music = [
  {
    title: `In the Aeroplane Over the Sea`,
    artist: `Neutral Milk Hotel`,
    year: 1998,
    runtime: 39.55,
    cover: `https://upload.wikimedia.org/wikipedia/en/8/83/In_the_aeroplane_over_the_sea_album_cover_copy.jpg`,
    genre: [`Indie Rock`, `Psychedelic folk`, `Lo-Fi`],
    ten: true,
  },
  {
    title: `Twin Fantasy`,
    artist: `Car Seat Headrest`,
    year: 2011,
    runtime: 60.26,
    cover: `https://upload.wikimedia.org/wikipedia/en/e/e0/Twin_fantasy.jpg`,
    genre: [`Indie Rock`, `Lo-Fi`, `Alternative Rock`],
    ten: false,
  },
  {
    title: `Loveless`,
    artist: `My Bloody Valentine`,
    year: 1991,
    runtime: 48.31,
    cover: `https://upload.wikimedia.org/wikipedia/en/4/4b/My_Bloody_Valentine_-_Loveless.png?20170328161417`,
    genre: [`Shoegaze`, `Dream Pop`, `Noise Rock`, `Avant-Rock`],
    ten: true,
  },
  {
    title: `Pinkerton`,
    artist: `Weezer`,
    year: 1996,
    runtime: 34.36,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/c/ca/Pinkerton_cover.jpg/220px-Pinkerton_cover.jpg`,
    genre: [`Alternative Rock`, `Power Pop`, `Emo`, `Pop Punk`, `Lo-Fi`],
    ten: true,
  },
  {
    title: `Ants from Up There`,
    artist: `Black Country, New Road`,
    year: 2022,
    runtime: 58.46,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/Ants_from_Up_There_-_Black_Country%2C_New_Road.jpg/220px-Ants_from_Up_There_-_Black_Country%2C_New_Road.jpg`,
    genre: [`Post-Rock`, `Chamber Pop`, `Art Rock`],
    ten: false,
  },
  {
    title: `Lift Your Skinny Fists Like Antennas to Heaven`,
    artist: `Godspeed You! Black Emperor`,
    year: 2000,
    runtime: 87.21,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Liftyrskinnyfists.jpg/220px-Liftyrskinnyfists.jpg`,
    genre: [`Post-Rock`],
    ten: false,
  },
  {
    title: `Deathconsciousness`,
    artist: `Have a Nice Life`,
    year: 2008,
    runtime: 85.04,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Have_a_nice_life_deathconsciousness.jpg/220px-Have_a_nice_life_deathconsciousness.jpg`,
    genre: [
      `Shoegaze`,
      `Post-Rock`,
      `Dark Ambient`,
      `Gothic Rock`,
      `Industrial Rock`,
    ],
    ten: false,
  },
  {
    title: `Pet Sounds`,
    artist: `The Beach Boys`,
    year: 1966,
    runtime: 35.57,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/b/bb/PetSoundsCover.jpg/220px-PetSoundsCover.jpg`,
    genre: [`Progressive Pop`, `Chamber Pop`, `Psychedelic Pop`, `Art Rock`],
    ten: true,
  },
  {
    title: `The Queen Is Dead`,
    artist: `The Smiths`,
    year: 1986,
    runtime: 36.48,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/The-Queen-is-Dead-cover.png/220px-The-Queen-is-Dead-cover.png`,
    genre: [`Indie Pop`, `Alternative Rock`, `Indie Rock`, `Post-Punk`],
    ten: true,
  },
  {
    title: `IGOR`,
    artist: `Tyler, the Creator`,
    year: 2019,
    runtime: 39.43,
    cover: `https://upload.wikimedia.org/wikipedia/en/5/51/Igor_-_Tyler%2C_the_Creator.jpg`,
    genre: [`Hip Hop`, `Funk`, `R&B`, `Neo Soul`],
    ten: false,
  },
  {
    title: `Entertainment!`,
    artist: `Gang of Four`,
    year: 1979,
    runtime: 39.53,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Entertainment%21.jpg/220px-Entertainment%21.jpg`,
    genre: [`Post-Punk`, `Dance-Punk`, `Art Punk`],
    ten: false,
  },
  {
    title: `Spiderland`,
    artist: `Slint`,
    year: 1991,
    runtime: 39.31,
    cover: `https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Slint_-_Spiderland.jpg/220px-Slint_-_Spiderland.jpg`,
    genre: [`Post-Hardcore`, `Post-Rock`, `Math Rock`],
    ten: true,
  },
];
